name: vpn_connection_monitor
description: VPN connection monitoring in Dart. Singleton class with state stream & connection check.
repository: https://github.com/bazl-E/Vpn_connection_monitor
homepage: https://github.com/bazl-E/Vpn_connection_monitor

version: 1.0.4

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  connectivity_plus: ^4.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: ^2.1.1

flutter:
  uses-material-design: true
